### ISSUE TITLE
Android incorrect assets folder location.

### ISSUE THREAD

**Issue by Charanor** [czyzby/gdx-setup#49] opened 2017-04-18 19:24 UTC
Hey. I'm using a clean install (see exact settings below) and I can't access the assets folder when running the application on my android device. Accessing the assets works just fine on desktop. I use `Gdx.files.internal()` to try to access the assets folder. I've tried debugging the problem and these are some conclusions I've come to:

- The directory **exists** (`Gdx.files.internal("").exists()` is **true**).
- The directory has 3 other directories in it, `/images`, `/sounds`, `/webkit` (checked with `Gdx.files.internal("").list()`).
    - These directories are **empty**.
- My `build.gradle` in my android directory says `assets.srcDirs = ['../assets']`.
    - The folder `../assets` **does exist** but is _not_ the folder that `Gdx.files.internal()` points to.
    - It doesn't matter if that directory has files or not (tried putting libgdx128, libgdx64. etc. in `../assets` folder just in case).
- Refreshing gradle project doesn't help.

These are my settings in gdx-setup:

- Platforms **Android** and **Desktop**.
- Extentions **Freetype**
- Template **ApplicationAdapter**
- GDXVersion **1.9.6**
- Advanced:
    - Java **1.6**
    - Desktop **1.8**
    - Android Plugin **2.3.0**
    - Target API **25**
    - Build tools **25.0.2**
- Add gradle wrapper

Any help appreciated!

**Comment by czyzby** [comment] 2017-04-18 19:35
Are you facing this issue when running the application via an emulator or on an actual device?

We moved `assets/` to the root folder to make the folder structure more flexible and independent of chosen platform. Original `gdx-setup` puts `assets/` inside `android/` instead of the root directory. We tested Android project after moving the `assets/` to root and it seemed to work fine.

As a workaround, I suggest to try moving `assets/` to `android/` and changing all references in Gradle files to the new location. If that doesn't help, it might not be a `gdx-setup` problem. I'll try to reproduce the issue locally and let you know.

**Comment by Charanor** [comment] 2017-04-18 19:39
I'm running it from my own android device (Sony Xperia Z5 Compact). Reproducing should be easy - it's a completely clean install with the above settings. I'll try to put the `assets/` folder in `android/` and let you know if it works.

**Comment by czyzby** [comment] 2017-04-18 19:57
Could you check if you can run the application via the emulator? I've just installed API v. 25 with build tools at 25.0.2 and successfully ran an application with assets generated by the `gdx-setup`. What IDE are you using? Is the assets folder marked as Android resources root?

![assets](https://cloud.githubusercontent.com/assets/11707612/25150331/dde77d1a-2481-11e7-86c6-6f8d8595b054.png)

**Comment by Charanor** [comment] 2017-04-18 20:09
_Placing the `assets/` folder in the `android/` folder seems to have solved the problem._

-----

I'm using Eclipse as my IDE, and using an emulator produces the same result. My Eclipse doesn't mark folders like your IDE does so I can't be sure.

PS. If it wasn't clear - I can run the application just fine, it's just that it doesn't find the `assets` folder.

**Comment by czyzby** [comment] 2017-04-18 20:15
I'm glad it worked for you. I suggest you move to Android Studio if you plan on focusing on mobile platforms, though.

> PS. If it wasn't clear - I can run the application just fine, it's just that it doesn't find the `assets` folder.

Yes, I know. I generated a project with files (simple Scene2D template) that were loaded with `Gdx.files.internal` at runtime. I tested it a while back and while I'm unable to check it on an actual device right now, it looks like it's an Eclipse issue - maybe it has problems marking folders outside of `android/` directory as resources.

I'll reopen the issue if I'm able to reproduce it using Android Studio.

**Closed by czyzby** 2017-04-18 20:15 UTC

**Comment by czyzby** [comment] 2017-04-18 20:24
It does. Your IDE does not handle that. I might be wrong, but the Android plugin for Eclipse is no longer maintained and out of date.

![assets](https://cloud.githubusercontent.com/assets/11707612/25151416/ce07df1c-2485-11e7-9284-aa29f02bf9b0.png)

**Comment by Charanor** [comment] 2017-04-18 20:26
Alright, thanks for your help!

**Comment by czyzby** [comment] 2017-04-18 20:28
No problem. Try switching to IntelliJ/Android Studio with Eclipse key mappings. You won't look back. Trust me, I've been there. ;)

**Comment by kotcrab** [comment] 2017-04-18 21:27
Can confirm it works on my device when launched from IntelliJ, though I had to bump up `buildToolsVersion` before it created APK.

![2017-04-18_2322](https://cloud.githubusercontent.com/assets/4594081/25153829/4d65ae80-248e-11e7-9f65-a83463d909b8.png)

@czyzby Should we change default version?

> You won't look back. Trust me, I've been there. ;)

Yup, same here.

**Comment by czyzby** [comment] 2017-04-18 21:30
@kotcrab Yeah, `25.0.2` seems like a good idea.

**Comment by czyzby** [comment] 2017-04-18 21:31
I'll take care of it.
