### ISSUE TITLE
Cannot start generated Autumn MVC desktop application when the project was created alongside Android app

### ISSUE THREAD

**Issue by Humberd** [czyzby/gdx-setup#55] opened 2018-02-17 20:10 UTC
**Current behaviour:**
When running `DesktopLauncher.main()` form IntelliJ it throws the following exception

```error
java.lang.NoClassDefFoundError: com/github/czyzby/autumn/scanner/ClassScanner
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.github.czyzby.autumn.scanner.ClassScanner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
```

**Expected behaviour:**
Desktop App should launch properly.

**Steps to reproduce:**

1. Download `1.9.6-beta5.jar`
2. In the `Platforms` tab select `Desktop` and `Android`
3. In the `Templates` tab select `Autumn MVC + VisUI` 
4. Run `DesktopLauncher.main()`

**Specs:**

- Java 1.8.0_162
- Gradle 4.0.2
- IntelliJ 3.4

**Additional info**
When creating a project but without checking `Android` in `Platforms` tab the app starts successfully.

Edit:
It runs successfully using gradle task `run`

**Comment by czyzby** [comment] 2018-02-17 22:05
Cannot reproduce. Which IDE do you use? How do you import the project? If you are using IntelliJ, I suggest turning on `Build, Execution, Deployment > Build Tools > Gradle > Runner > Delegate IDE build/run actions to gradle` in `Settings`.

BTW, Autumn is mostly discontinued. I update it only every once in a while when I happen to have some free time, but I don't develop it actively anymore. You might want to look into [LibKTX](https://github.com/libktx/ktx) instead.

**Comment by czyzby** [comment] 2018-08-20 11:44
I cannot reproduce the error, so I'm going to close the issue for now. Feel free to reopen if the issue persists.

**Closed by czyzby** 2018-08-20 11:44 UTC
